<?php

namespace Cars\CoreBundle\Repository;

use Cars\CoreBundle\Entity\User;
use Cars\CoreBundle\Manager\UserManagerInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserManagerInterface
{

    public function createUser(array $data)
    {
    }

    public function deleteUser($userId = 0)
    {
        // TODO: Implement deleteUser() method.
    }

    public function findUserBy(array $criteria)
    {
        // TODO: Implement findUserBy() method.
    }
}
